"""
Level 4: LLM response generation with SSE streaming.
Handles both coupon responses and conversational narrowing questions.
"""

import json
import logging
import re
from pathlib import Path
from typing import AsyncIterator

from openai import AsyncOpenAI

import config
from llm.factory import get_llm
import conversation as conv
import llm_logger

log = logging.getLogger(__name__)


def _load_prompt(filename: str) -> str:
    path = config.PROMPTS_DIR / filename
    return path.read_text(encoding="utf-8")


def _coupon_summary(coupons: list[dict]) -> str:
    """Build a compact natural-language summary of the coupon batch for the LLM prompt."""
    if not coupons:
        return "no coupons found"
    top3      = coupons[:3]
    # Sample stores from the FULL result set, not just the first 3 — when multiple
    # verticals/stores are merged (e.g. Laptop + Cab), the first 3 entries can all
    # belong to whichever group was fetched first, silently hiding the others
    # from the summary the LLM uses to write its opening sentence.
    stores    = sorted({c.get("StoreName", "") for c in coupons if c.get("StoreName")})
    n_codes   = sum(1 for c in top3 if (c.get("CouponCode") or "").strip())
    n_today   = sum(1 for c in coupons if c.get("validity_urgency") == "expires_today")
    n_soon    = sum(1 for c in coupons if c.get("validity_urgency") == "expires_soon")
    store_str = ", ".join(stores[:3]) + ("..." if len(stores) > 3 else "")
    parts     = [f"Found top deals across: {store_str}."]
    if n_codes:
        parts.append(f"{n_codes} of the top picks have coupon codes to copy.")
    else:
        parts.append("These are deal links (no code needed).")
    if n_today:
        parts.append(f"⚠️ {n_today} expire TODAY — act fast!")
    elif n_soon:
        parts.append(f"{n_soon} expiring soon.")
    return " ".join(parts)


def _history_to_messages(history: list[conv.Message]) -> list[dict]:
    return [{"role": m.role, "content": m.content} for m in history]


def _get_system_prompt(for_narrowing: bool = False) -> str:
    if for_narrowing:
        return _load_prompt("narrowing.txt")
    provider = config.LLM_PROVIDER.lower()
    filename = f"respond_{provider}.txt"
    if not (config.PROMPTS_DIR / filename).exists():
        filename = "respond_ollama.txt"
    return _load_prompt(filename)


async def stream_narrowing_question(
    clarification_question: str,
    user_message: str,
    session_id: str,
) -> AsyncIterator[str]:
    """
    Stream clarification question for vague (Type C) queries.
    The question is already generated by the LLM classifier — yield it directly.
    Falls back to a second LLM call only if the classifier returned nothing.
    """
    if clarification_question:
        yield clarification_question
        return

    # Fallback: ask LLM to generate a narrowing question
    history  = conv.get_history(session_id)
    messages = _history_to_messages(history)
    messages.append({"role": "user", "content": user_message})

    system = _get_system_prompt(for_narrowing=True)
    llm    = get_llm()
    async for chunk in llm.generate(
        system_prompt = system,
        messages      = messages,
        temperature   = config.LLM_RESPOND_TEMPERATURE,
        max_tokens    = 150,
    ):
        yield chunk
    llm_logger.log_call(
        model         = llm.model,
        prompt_file   = "narrowing.txt",
        function_name = "stream_narrowing_question",
        input_tokens  = llm.last_usage.get("input_tokens", 0),
        output_tokens = llm.last_usage.get("output_tokens", 0),
        session_id    = session_id,
    )


_openai_client: AsyncOpenAI | None = None


def _get_openai() -> AsyncOpenAI:
    global _openai_client
    if _openai_client is None:
        _openai_client = AsyncOpenAI(api_key=config.OPENAI_API_KEY)
    return _openai_client


async def filter_brand_coupons(brand: str, coupons: list[dict]) -> list[dict]:
    """
    gpt-4o-mini verifies which CouponName-LIKE results are genuinely for the
    requested brand vs. just mentioning it incidentally (e.g. multi-brand listings).
    Returns [] if nothing qualifies. Falls back to all on parse error.
    """
    def _disc(c: dict) -> str:
        disp = c.get("discount_display") or ""
        if disp:
            return disp
        d = c.get("Discount")
        return f"{int(d)}% OFF" if d else "flat discount"

    index_map = {
        i: {
            "store":    c.get("StoreName") or "",
            "name":     (c.get("CouponName") or "").strip(),
            "discount": _disc(c),
        }
        for i, c in enumerate(coupons)
    }

    prompt = (
        f"User asked for \"{brand}\" coupons.\n\n"
        f"These coupons were found by searching CouponName for \"{brand}\":\n"
        f"{json.dumps(index_map, indent=2)}\n\n"
        f"KEEP a coupon if ANY of these are true:\n"
        f"  - The store name contains \"{brand}\"\n"
        f"  - The coupon name mentions buying, purchasing, or getting a discount specifically on {brand} products\n"
        f"  - The coupon is a {brand}-specific offer (e.g. \"{brand} Special Offer\", \"Purchase Of {brand}\")\n"
        f"EXCLUDE only if {brand} appears alongside 5+ other brand names (pure multi-brand listing) "
        f"or is mentioned completely incidentally with no relation to the discount.\n"
        f"When in doubt, KEEP the coupon.\n"
        f"Return a JSON array of indices only, e.g. [0, 2]. Return [] if none qualify. No explanation."
    )

    try:
        client = _get_openai()
        resp = await client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"},
            temperature=0,
            max_tokens=100,
        )
        llm_logger.log_call(
            model         = "gpt-4o-mini",
            prompt_file   = "inline: brand_filter",
            function_name = "filter_brand_coupons",
            input_tokens  = resp.usage.prompt_tokens     or 0,
            output_tokens = resp.usage.completion_tokens or 0,
        )
        raw = resp.choices[0].message.content or ""
        parsed = json.loads(raw)
        indices = parsed if isinstance(parsed, list) else next(
            (v for v in parsed.values() if isinstance(v, list)), None
        )
        if indices is None:
            return coupons  # parse error → safe fallback
        return [coupons[i] for i in indices if 0 <= i < len(coupons)]
    except Exception as e:
        log.warning("Brand coupon filter failed, returning all: %s", e)
        return coupons


async def _filter_relevant_coupons(coupons: list[dict], user_message: str) -> list[dict]:
    """
    Ask gpt-4o-mini which coupons are genuinely relevant to the user's request.
    Works for routes, cities, user type, dietary preference — anything in the name.
    Falls back to all coupons on error or if LLM keeps none.
    """
    def _discount_str(c: dict) -> str:
        disp = c.get("discount_display") or ""
        if disp:
            return disp
        d = c.get("Discount")
        return f"{int(d)}% OFF" if d else "flat discount"

    index_map = {}
    for i, c in enumerate(coupons):
        index_map[i] = {
            "store":    c.get("StoreName") or "",
            "name":     (c.get("CouponName") or "").strip(),
            "discount": _discount_str(c),
            "validity": c.get("validity_label") or "No expiry",
        }

    prompt = (
        f"User request: \"{user_message}\"\n\n"
        f"Here are the coupons retrieved from the database:\n"
        f"{json.dumps(index_map, indent=2)}\n\n"
        f"Keep only coupons genuinely relevant to what the user asked for.\n"
        f"Rules (apply the first rule that fits):\n"
        f"1. If the user named a specific BRAND or MANUFACTURER (Apple, Samsung, Nike, Puma, etc.):\n"
        f"   - KEEP if the store name contains the brand. DROP if clearly a different brand.\n"
        f"2. If the user named specific CATEGORIES or PRODUCTS (school bags, stationery, groceries, clothing, electronics, food, travel, etc.):\n"
        f"   - KEEP only coupons whose store name or coupon name clearly relates to those categories.\n"
        f"   - DROP coupons from unrelated categories (e.g. audio apps, ebook stores when user asked for school bags or stationery).\n"
        f"3. If the user asked for new-user / first-order coupons — keep ONLY coupons whose name mentions first order, new user, welcome, signup.\n"
        f"4. If the request is completely vague with no brand, category, or product mentioned — keep ALL coupons.\n"
        f"Return [] only if nothing is genuinely relevant. No explanation — return ONLY a JSON array of indices, e.g. [0, 2, 5]."
    )

    try:
        client = _get_openai()
        resp = await client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"},
            temperature=0,
            max_tokens=200,
        )
        llm_logger.log_call(
            model         = "gpt-4o-mini",
            prompt_file   = "inline: relevance_filter",
            function_name = "_filter_relevant_coupons",
            input_tokens  = resp.usage.prompt_tokens     or 0,
            output_tokens = resp.usage.completion_tokens or 0,
        )
        raw = resp.choices[0].message.content or ""
        # response_format=json_object wraps in an object; extract first array value
        parsed = json.loads(raw)
        if isinstance(parsed, list):
            indices = parsed
        else:
            indices = next((v for v in parsed.values() if isinstance(v, list)), None)
        if indices is None:
            # Couldn't parse response — safe fallback to all
            return coupons
        # indices == [] means the LLM intentionally found nothing relevant — respect it
        filtered = [coupons[i] for i in indices if 0 <= i < len(coupons)]
        return filtered  # may be []
    except Exception as e:
        log.warning("Relevance filter failed, returning all coupons: %s", e)
        return coupons


def serialise_coupons(coupons: list[dict]) -> list[dict]:
    """Public wrapper used by main.py to emit coupons without a full LLM call."""
    return _serialise_coupons(_prioritise_coupons(coupons))


def _prioritise_coupons(coupons: list[dict]) -> list[dict]:
    """Put coupons with actual codes first; deal-link-only coupons last."""
    with_code    = [c for c in coupons if (c.get("CouponCode") or "").strip()]
    without_code = [c for c in coupons if not (c.get("CouponCode") or "").strip()]
    return with_code + without_code


async def stream_coupon_response(
    user_message: str,
    session_id: str,
    coupons: list[dict],
    pending_offer: str = "",
    skip_relevance_filter: bool = False,
) -> AsyncIterator[str | dict]:
    """
    Stream the LLM coupon response.
    Yields str chunks (text tokens) then a final dict {"type": "coupons", "data": [...]}.
    Pass skip_relevance_filter=True when coupons have already been verified upstream
    (e.g. via filter_brand_coupons) to avoid double-filtering.
    """
    if not skip_relevance_filter:
        coupons = await _filter_relevant_coupons(coupons, user_message)
    if not coupons:
        yield "I couldn't find coupons that specifically match what you're looking for on GrabOn right now."
        return

    coupons  = _prioritise_coupons(coupons)

    history  = conv.get_history(session_id)
    messages = _history_to_messages(history)
    messages.append({"role": "user", "content": user_message})

    summary    = _coupon_summary(coupons)
    system_raw = _get_system_prompt(for_narrowing=False)
    system     = system_raw.replace("{coupon_summary}", summary)

    llm = get_llm()

    async for chunk in llm.generate(
        system_prompt = system,
        messages      = messages,
        temperature   = config.LLM_RESPOND_TEMPERATURE,
        max_tokens    = config.LLM_MAX_TOKENS,
    ):
        yield chunk

    llm_logger.log_call(
        model         = llm.model,
        prompt_file   = f"respond_{config.LLM_PROVIDER}.txt",
        function_name = "stream_coupon_response",
        input_tokens  = llm.last_usage.get("input_tokens", 0),
        output_tokens = llm.last_usage.get("output_tokens", 0),
        session_id    = session_id,
    )

    # After text stream, emit structured coupon data
    yield {"type": "coupons", "data": _serialise_coupons(coupons)}


async def stream_no_results_response(
    category: str,
) -> AsyncIterator[str]:
    """Inform user no DB coupons found and offer web search. LLM generates the message."""
    template = _load_prompt("no_results.txt")
    prompt   = template.replace("{category}", category)
    llm = get_llm()
    async for chunk in llm.generate(
        system_prompt = "You are GrabGPT, a friendly coupon assistant for GrabOn.in.",
        messages      = [{"role": "user", "content": prompt}],
        temperature   = 0.3,
        max_tokens    = 100,
    ):
        yield chunk
    llm_logger.log_call(
        model         = llm.model,
        prompt_file   = "no_results.txt",
        function_name = "stream_no_results_response",
        input_tokens  = llm.last_usage.get("input_tokens", 0),
        output_tokens = llm.last_usage.get("output_tokens", 0),
    )


async def stream_dual_no_results_response(
    category: str,
    related_label: str,
) -> AsyncIterator[str]:
    """No DB coupons for specific category but related exist. Offers related GrabOn deals only."""
    prompt = (
        f"We don't have {category} coupons on GrabOn right now, "
        f"but we have deals for {related_label}. "
        f"Ask the user if they'd like to see those {related_label} offers instead. "
        f"Keep it to 2 sentences, warm and natural. No em dashes. No exclamation marks."
    )
    llm = get_llm()
    async for chunk in llm.generate(
        system_prompt = "You are GrabGPT, a friendly coupon assistant for GrabOn.in.",
        messages      = [{"role": "user", "content": prompt}],
        temperature   = 0.3,
        max_tokens    = 100,
    ):
        yield chunk
    llm_logger.log_call(
        model         = llm.model,
        prompt_file   = "inline: dual_no_results",
        function_name = "stream_dual_no_results_response",
        input_tokens  = llm.last_usage.get("input_tokens", 0),
        output_tokens = llm.last_usage.get("output_tokens", 0),
    )


async def stream_clarification_response(
    category: str,
) -> AsyncIterator[str]:
    """User said 'yes' when related offers were on the table — LLM asks them to clarify."""
    prompt = (
        f"The user said yes but it's unclear what they want. "
        f"Ask them to clarify if they want to see the related {category} offers on GrabOn. "
        f"Keep it short and warm. No em dashes. No exclamation marks."
    )
    llm = get_llm()
    async for chunk in llm.generate(
        system_prompt = "You are GrabGPT, a friendly coupon assistant for GrabOn.in.",
        messages      = [{"role": "user", "content": prompt}],
        temperature   = 0.3,
        max_tokens    = 100,
    ):
        yield chunk
    llm_logger.log_call(
        model         = llm.model,
        prompt_file   = "inline: clarification",
        function_name = "stream_clarification_response",
        input_tokens  = llm.last_usage.get("input_tokens", 0),
        output_tokens = llm.last_usage.get("output_tokens", 0),
    )


_WEB_JUNK_RE = re.compile(
    r'(https?://|www\.|\.com|\.in|visit deal|visit site|click here|get deal|'
    r'visit now|check here|click deal|grab deal)',
    re.I,
)
_CODE_LIKE_RE = re.compile(r'\b[A-Z0-9]{4,20}\b')

# Snippets mentioning past years or explicit "expired" wording are unreliable
_STALE_RE = re.compile(
    r'\b(expired?|invalid|no longer|202[0-4])\b',
    re.I,
)


def _extract_codes_from_snippets(web_results: list[dict]) -> list[str]:
    """Regex-extract alphanumeric coupon codes directly from SearXNG snippets."""
    _BLOCKLIST = {
        "HTML", "HTTP", "HTTPS", "DEAL", "COUPON", "OFFER", "VISIT", "CODE",
        "SAVE", "FREE", "FLAT", "UPTO", "BEST", "ALSO", "APPLY", "LINK",
        "VIEW", "SALE", "BOOK", "SHOP", "CLICK", "HERE", "PAGE", "READ",
        "USER", "EMAIL", "LAST", "DAYS", "FROM", "SITE", "MORE", "GRAB",
        "INDIA", "CASH", "BACK", "NEW", "OLD", "GET", "OFF", "USE",
    }
    found = []
    seen: set[str] = set()
    for r in web_results:
        snippet = r.get("title", "") + " " + r.get("content", "")
        # Skip snippets that mention expiry or past years — likely stale
        if _STALE_RE.search(snippet):
            continue
        text = snippet.upper()
        for code in _CODE_LIKE_RE.findall(text):
            if (code not in _BLOCKLIST
                    and not code.isdigit()      # skip pure numbers like "2026"
                    and len(code) >= 4
                    and code not in seen):
                seen.add(code)
                found.append(code)
    return found[:8]


async def stream_web_results_response(
    user_message: str,
    session_id: str,
    web_results: list[dict],
    category: str,
) -> AsyncIterator[str]:
    """Present web search results as coupon codes only — no website links."""
    if not web_results:
        yield f"No active coupon codes for {category} found right now."
        return

    # First try regex extraction from snippets (fast, no hallucination risk)
    regex_codes = _extract_codes_from_snippets(web_results)
    if regex_codes:
        lines = [
            f"Here are some {category} coupon codes I found on the web "
            f"(not verified by GrabOn — apply at checkout to confirm):\n"
        ]
        for code in regex_codes:
            lines.append(f"**{code}**")
        yield "\n".join(lines)
        return

    # Fallback: LLM extraction using prompt file
    web_context = "\n\n".join(
        f"Source: {r['title']}\nSnippet: {r['content']}"
        for r in web_results
    )
    prompt_template = _load_prompt("extract_web_codes.txt")
    system = prompt_template.replace("{web_context}", web_context)

    history  = conv.get_history(session_id)
    messages = _history_to_messages(history)
    messages.append({"role": "user", "content": user_message})
    llm = get_llm()

    buffered = ""
    async for chunk in llm.generate(
        system_prompt = system,
        messages      = messages,
        temperature   = 0.0,
        max_tokens    = 300,
    ):
        buffered += chunk
    llm_logger.log_call(
        model         = llm.model,
        prompt_file   = "extract_web_codes.txt",
        function_name = "stream_web_results_response",
        input_tokens  = llm.last_usage.get("input_tokens", 0),
        output_tokens = llm.last_usage.get("output_tokens", 0),
        session_id    = session_id,
    )

    # Post-filter: remove any line that looks like junk (URLs, "Visit Deal", etc.)
    if "NO_CODES_FOUND" in buffered.upper() or not buffered.strip():
        yield f"No active coupon codes for {category} found right now."
        return

    clean_lines = [
        line for line in buffered.splitlines()
        if line.strip() and not _WEB_JUNK_RE.search(line)
    ]

    if not clean_lines:
        yield f"No active coupon codes for {category} found right now."
        return

    header = (
        f"Here are some {category} coupon codes I found on the web "
        f"(not verified by GrabOn — use at your own discretion):\n\n"
    )
    yield header + "\n".join(clean_lines)


def _serialise_coupons(coupons: list[dict]) -> list[dict]:
    """Convert coupon dicts to JSON-safe format for the frontend."""
    safe = []
    for c in coupons:
        safe.append({
            "couponId":         c.get("CouponID"),
            "storeName":        c.get("StoreName", ""),
            "couponName":       c.get("CouponName", ""),
            "couponCode":       c.get("CouponCode") or "",
            "couponUrl":        c.get("CouponUrl") or "",
            "couponTypeId":     c.get("CouponTypeID"),
            "discount":         float(c["Discount"]) if c.get("Discount") else 0,
            "discountDisplay":  c.get("discount_display", ""),
            "minOrderAmount":   float(c["MinimumOrderAmount"]) if c.get("MinimumOrderAmount") else None,
            "maxDiscount":      float(c["MaximumDiscount"]) if c.get("MaximumDiscount") else None,
            "verified":         bool(c.get("Verified")),
            "exclusive":        bool(c.get("Exclusive")),
            "hotOffer":         bool(c.get("HotOffer")),
            "bestOffer":        bool(c.get("BestOffer")),
            "forExistingUser":  bool(c.get("ForExistingUser")),
            "validityLabel":    c.get("validity_label", ""),
            "validityUrgency":  c.get("validity_urgency", "valid"),
            "endDate":          c["EndDate"].isoformat() if c.get("EndDate") else None,
        })
    return safe
