"""
Level 4: LLM response generation with SSE streaming.
Handles both coupon responses and conversational narrowing questions.
"""

import json
import logging
from pathlib import Path
from typing import AsyncIterator

from openai import AsyncOpenAI

import config
import coupon_tiers
from llm.factory import get_llm
import conversation as conv
import llm_logger

log = logging.getLogger(__name__)


def _load_prompt(filename: str) -> str:
    path = config.PROMPTS_DIR / filename
    return path.read_text(encoding="utf-8")


def _coupon_summary(coupons: list[dict]) -> str:
    """
    Compact, fully-accurate natural-language summary for the LLM prompt.
    The response prompt cites facts straight from this string, so every fact
    here must be literally true -- an ambiguous or missing figure is exactly
    what causes the model to invent one instead.
    """
    if not coupons:
        return "no coupons found"
    # Sample stores from the FULL result set, not just the first 3 — when multiple
    # verticals/stores are merged (e.g. Laptop + Cab), the first 3 entries can all
    # belong to whichever group was fetched first, silently hiding the others
    # from the summary the LLM uses to write its opening sentence.
    stores  = sorted({c.get("StoreName", "") for c in coupons if c.get("StoreName")})
    n_today = sum(1 for c in coupons if c.get("validity_urgency") == "expires_today")
    n_soon  = sum(1 for c in coupons if c.get("validity_urgency") == "expires_soon")
    # Only trust Discount as a clean percentage when CouponTypeID says it actually
    # IS one (type 2) -- some rows store a flat rupee amount or a promo-mechanic ID
    # in the same column, so "% off" would be a lie for those.
    pct_discounts = [c.get("Discount") or 0 for c in coupons if c.get("CouponTypeID") == 2]
    best_pct = max(pct_discounts) if pct_discounts else 0

    store_str = ", ".join(stores[:3]) + ("..." if len(stores) > 3 else "")
    parts = [f"Found top deals across: {store_str}.", f"{len(coupons)} deals found."]
    if n_today:
        parts.append(f"{n_today} expire TODAY.")
    elif n_soon:
        parts.append(f"{n_soon} expiring soon.")
    if best_pct >= 50:
        parts.append(f"Top discount: {int(best_pct)}% off.")
    return " ".join(parts)


def _history_to_messages(history: list[conv.Message]) -> list[dict]:
    return [{"role": m.role, "content": m.content} for m in history]


def _get_system_prompt(for_narrowing: bool = False) -> str:
    if for_narrowing:
        return _load_prompt("narrowing.txt")
    provider = config.LLM_PROVIDER.lower()
    filename = f"respond_{provider}.txt"
    if not (config.PROMPTS_DIR / filename).exists():
        filename = "respond_ollama.txt"
    return _load_prompt(filename)


async def stream_narrowing_question(
    clarification_question: str,
    user_message: str,
    session_id: str,
) -> AsyncIterator[str]:
    """
    Stream clarification question for vague (Type C) queries.
    The question is already generated by the LLM classifier — yield it directly.
    Falls back to a second LLM call only if the classifier returned nothing.
    """
    if clarification_question:
        yield clarification_question
        return

    # Fallback: ask LLM to generate a narrowing question
    history  = conv.get_history(session_id)
    messages = _history_to_messages(history)
    messages.append({"role": "user", "content": user_message})

    system = _get_system_prompt(for_narrowing=True)
    llm    = get_llm()
    async for chunk in llm.generate(
        system_prompt = system,
        messages      = messages,
        temperature   = config.LLM_RESPOND_TEMPERATURE,
        max_tokens    = 150,
    ):
        yield chunk
    llm_logger.log_call(
        model         = llm.model,
        prompt_file   = "narrowing.txt",
        function_name = "stream_narrowing_question",
        input_tokens  = llm.last_usage.get("input_tokens", 0),
        output_tokens = llm.last_usage.get("output_tokens", 0),
        session_id    = session_id,
    )


async def stream_unavailable_response(
    user_message: str,
    session_id: str,
    subject: str,
) -> AsyncIterator[str]:
    """
    Warm, natural "we don't have that right now" reply that explicitly names
    what was asked for -- never a stock template, never the same wording twice.
    No alternative store/category is ever suggested; this only declines and
    invites the user to ask for something else.
    """
    prompt = (
        f"The user asked for coupons related to \"{subject}\", but GrabOn has no "
        f"active coupon codes for that right now.\n\n"
        f"Write a warm, natural, one-off reply telling them this plainly and "
        f"politely. Mention \"{subject}\" by name so they know you understood "
        f"exactly what they asked for. Do not suggest any other store or "
        f"category yourself -- just invite them to ask for something else if "
        f"they'd like.\n\n"
        f"Vary your phrasing every time, including your OPENING WORDS -- do not "
        f"default to \"I understand you're looking for...\" or any other fixed "
        f"opener. Pick a fresh angle each time: sometimes lead with the apology, "
        f"sometimes with the store name, sometimes with the invitation to ask "
        f"for something else. Never reuse a stock template.\n\n"
        f"Max 2 sentences, under 35 words. No em dashes. No exclamation marks. "
        f"No corporate phrasing (\"I'd be happy to\")."
    )
    history  = conv.get_history(session_id)
    messages = _history_to_messages(history)
    messages.append({"role": "user", "content": prompt})

    llm = get_llm()
    full_text = ""
    async for chunk in llm.generate(
        system_prompt = "You are GrabonGPT, a friendly coupon assistant for GrabOn.in.",
        messages      = messages,
        temperature   = 0.8,  # higher than normal -- the whole point is varied phrasing
        max_tokens    = 80,
    ):
        yield chunk
        full_text += chunk
    llm_logger.log_call(
        model         = llm.model,
        prompt_file   = "inline: unavailable_response",
        function_name = "stream_unavailable_response",
        input_tokens  = llm.last_usage.get("input_tokens", 0),
        output_tokens = llm.last_usage.get("output_tokens", 0),
        session_id    = session_id,
    )


_openai_client: AsyncOpenAI | None = None


def _get_openai() -> AsyncOpenAI:
    global _openai_client
    if _openai_client is None:
        _openai_client = AsyncOpenAI(api_key=config.OPENAI_API_KEY)
    return _openai_client


async def filter_brand_coupons(brand: str, coupons: list[dict]) -> list[dict]:
    """
    gpt-4o-mini verifies which CouponName-LIKE results are genuinely for the
    requested brand vs. just mentioning it incidentally (e.g. multi-brand listings).
    Returns [] if nothing qualifies. Falls back to all on parse error.
    """
    def _disc(c: dict) -> str:
        disp = c.get("discount_display") or ""
        if disp:
            return disp
        d = c.get("Discount")
        return f"{int(d)}% OFF" if d else "flat discount"

    index_map = {
        i: {
            "store":    c.get("StoreName") or "",
            "name":     (c.get("CouponName") or "").strip(),
            "discount": _disc(c),
        }
        for i, c in enumerate(coupons)
    }

    prompt = (
        f"User asked for \"{brand}\" coupons.\n\n"
        f"These coupons were found by searching CouponName for \"{brand}\":\n"
        f"{json.dumps(index_map, indent=2)}\n\n"
        f"KEEP a coupon if ANY of these are true:\n"
        f"  - The store name contains \"{brand}\"\n"
        f"  - The coupon name mentions buying, purchasing, or getting a discount specifically on {brand} products\n"
        f"  - The coupon is a {brand}-specific offer (e.g. \"{brand} Special Offer\", \"Purchase Of {brand}\")\n"
        f"EXCLUDE only if {brand} appears alongside 5+ other brand names (pure multi-brand listing) "
        f"or is mentioned completely incidentally with no relation to the discount.\n"
        f"When in doubt, KEEP the coupon.\n"
        f"Return a JSON array of indices only, e.g. [0, 2]. Return [] if none qualify. No explanation."
    )

    try:
        client = _get_openai()
        resp = await client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"},
            temperature=0,
            max_tokens=100,
        )
        llm_logger.log_call(
            model         = "gpt-4o-mini",
            prompt_file   = "inline: brand_filter",
            function_name = "filter_brand_coupons",
            input_tokens  = resp.usage.prompt_tokens     or 0,
            output_tokens = resp.usage.completion_tokens or 0,
        )
        raw = resp.choices[0].message.content or ""
        parsed = json.loads(raw)
        indices = parsed if isinstance(parsed, list) else next(
            (v for v in parsed.values() if isinstance(v, list)), None
        )
        if indices is None:
            return coupons  # parse error → safe fallback
        # Defensive: the model can occasionally return a malformed shape (e.g. a
        # nested list) even under json_object mode -- only trust plain ints.
        return [coupons[i] for i in indices if isinstance(i, int) and 0 <= i < len(coupons)]
    except Exception as e:
        log.warning("Brand coupon filter failed, returning all: %s", e)
        return coupons


async def _classify_relevant_groups(
    groups: dict[str, list[dict]], user_message: str
) -> dict[str, list[int]]:
    """
    One combined gpt-4o-mini call. `groups` maps an item label (e.g. "bus", "hotel",
    or "_single" for a one-item query) to a list of {"store", "name"} candidates
    (sitewide and synonym-tier coupons from a single-store pool are already pulled
    out in pure Python before this is called -- the LLM's only job is semantic
    relevance, nothing it could get by exact keyword match).

    The store name travels with each candidate specifically so the model can judge
    STORE-TYPE fit, not just literal keyword overlap in the coupon text -- a broad
    vertical mixes unrelated businesses (a bakery next to a food-delivery platform),
    and without knowing which store a coupon belongs to, "no literal keyword match"
    and "wrong kind of business entirely" look identical to a text-only filter.

    Returns {label: [indices into that group's own list]}. Empty list per group on
    error or when that item's ask was generic (no specific product/category).
    """
    non_empty = {k: v for k, v in groups.items() if v}
    if not non_empty:
        return {k: [] for k in groups}

    prompt = (
        f"User asked: \"{user_message}\"\n\n"
        f"Coupons grouped by item, each with its store:\n{json.dumps(non_empty, indent=2)}\n\n"
        f"For EACH group, return the indices (within that group's own list) of coupons "
        f"that genuinely match what the user asked for regarding that specific item "
        f"(a brand, product type, or category mentioned in the request).\n"
        f"Judge by STORE TYPE, not just literal keyword overlap in the coupon name:\n"
        f"  - KEEP a store whose business plausibly sells or delivers what was asked, "
        f"even if the coupon text is generic (e.g. a food-delivery platform's 'flat "
        f"50% off orders' coupon is a genuine match for a biriyani/noodles/veg-meal request).\n"
        f"  - EXCLUDE a store whose business is clearly the wrong category for what was "
        f"asked, even if its coupon looks like a big generic discount (e.g. a bakery or "
        f"cake shop is NOT a match for a biriyani/noodles request just because it has a "
        f"sitewide-sounding offer -- wrong kind of business beats any discount size).\n"
        f"If the ask for an item was a generic store-only request with no specific "
        f"product/category, return [] for that group — a generic ask has nothing to "
        f"be more specific than.\n"
        f"Return ONLY a JSON object mapping each group key to an array of indices, e.g. "
        f'{{"bus": [0, 2], "hotel": []}}. No explanation.'
    )

    try:
        client = _get_openai()
        resp = await client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"},
            temperature=0,
            max_tokens=300,
        )
        llm_logger.log_call(
            model         = "gpt-4o-mini",
            prompt_file   = "inline: tier_relevance",
            function_name = "_classify_relevant_groups",
            input_tokens  = resp.usage.prompt_tokens     or 0,
            output_tokens = resp.usage.completion_tokens or 0,
        )
        raw = resp.choices[0].message.content or ""
        parsed = json.loads(raw)
        # Defensive: only trust plain ints -- the model can occasionally return a
        # malformed shape (e.g. a nested list) even under json_object mode, and a
        # non-int index would blow up the range check wherever this is consumed.
        def _clean(v):
            return [x for x in v if isinstance(x, int)] if isinstance(v, list) else []
        return {k: _clean(parsed.get(k)) for k in groups}
    except Exception as e:
        log.warning("Relevance classification failed, treating all as non-specific: %s", e)
        return {k: [] for k in groups}


def _discount_value(c: dict) -> float:
    return float(c.get("Discount") or 0)


async def select_top_coupons_for_items(
    item_coupons: dict[str, list[dict]],
    user_message: str,
    quota_per_item: int,
) -> dict[str, list[dict]]:
    """
    4-tier priority fill, per item: sitewide -> relevant -> synonym -> best-discount
    catch-all. Always tries to fill `quota_per_item` by falling through tiers in
    order. One combined LLM call covers relevance for every item at once.
    Dedups by exact CouponCode within each item's result (a coupon picked into an
    earlier tier is never eligible for a later tier).

    The sitewide/synonym keyword tiers only get priority when a group's pool is
    a SINGLE store (the user named a store, so "sitewide" means that store's
    own blanket offer -- inherently relevant). When a pool spans MULTIPLE
    different stores (a broad vertical with no store named, e.g. "biriyani"
    resolving to the whole Food vertical), a random store's "sitewide" wording
    says nothing about whether that store is even the right kind of business
    for what was asked -- treating it as automatic top priority is how an
    unrelated bakery's blanket discount out-ranks an actual food-delivery
    platform for a biriyani search. In that case everything goes through
    relevance judgment on equal footing instead.
    """
    per_item_tiers: dict[str, dict] = {}
    for label, coupons in item_coupons.items():
        merchant_ids = {c.get("MerchantID") for c in coupons if c.get("MerchantID") is not None}
        single_store = len(merchant_ids) <= 1

        sitewide, synonym, leftover = [], [], []
        if single_store:
            for c in coupons:
                tier = coupon_tiers.classify_keyword_tier(c.get("CouponName") or "")
                if tier == "sitewide":
                    sitewide.append(c)
                elif tier == "synonym":
                    synonym.append(c)
                else:
                    leftover.append(c)
        else:
            leftover = list(coupons)

        per_item_tiers[label] = {"sitewide": sitewide, "synonym": synonym, "leftover": leftover}

    name_groups = {
        label: [
            {"store": c.get("StoreName") or "", "name": (c.get("CouponName") or "").strip()}
            for c in t["leftover"]
        ]
        for label, t in per_item_tiers.items()
    }
    relevant_by_item = await _classify_relevant_groups(name_groups, user_message)

    results: dict[str, list[dict]] = {}
    for label, t in per_item_tiers.items():
        leftover = t["leftover"]
        rel_idx  = {i for i in (relevant_by_item.get(label) or []) if isinstance(i, int) and 0 <= i < len(leftover)}
        relevant  = [leftover[i] for i in sorted(rel_idx)]
        catch_all = [c for i, c in enumerate(leftover) if i not in rel_idx]

        buckets = [t["sitewide"], relevant, t["synonym"], catch_all]
        for b in buckets:
            b.sort(key=_discount_value, reverse=True)

        picked: list[dict] = []
        seen_codes: set[str] = set()
        for bucket in buckets:
            if len(picked) >= quota_per_item:
                break
            for c in bucket:
                if len(picked) >= quota_per_item:
                    break
                code = (c.get("CouponCode") or "").strip()
                if code and code in seen_codes:
                    continue  # already picked in an earlier tier — never show twice
                seen_codes.add(code)
                picked.append(c)
        results[label] = picked

    return results


async def select_top_coupons(coupons: list[dict], user_message: str, quota: int = 3) -> list[dict]:
    """Single-item convenience wrapper around select_top_coupons_for_items."""
    result = await select_top_coupons_for_items({"_single": coupons}, user_message, quota)
    return result["_single"]


def serialise_coupons(coupons: list[dict]) -> list[dict]:
    """Public wrapper used by main.py to emit coupons without a full LLM call."""
    return _serialise_coupons(_prioritise_coupons(coupons))


def _prioritise_coupons(coupons: list[dict]) -> list[dict]:
    """Put coupons with actual codes first; deal-link-only coupons last."""
    with_code    = [c for c in coupons if (c.get("CouponCode") or "").strip()]
    without_code = [c for c in coupons if not (c.get("CouponCode") or "").strip()]
    return with_code + without_code


async def stream_coupon_response(
    user_message: str,
    session_id: str,
    coupons: list[dict],
    pending_offer: str = "",
    quota: int = 3,
    already_selected: bool = False,
) -> AsyncIterator[str | dict]:
    """
    Stream the LLM coupon response.
    Yields str chunks (text tokens) then a final dict {"type": "coupons", "data": [...]}.
    By default runs the 4-tier priority selector (sitewide -> relevant -> synonym ->
    best-discount), always capping to `quota`. Pass already_selected=True only when
    the caller already ran select_top_coupons_for_items across multiple items and
    merged the results — re-running selection on a mixed multi-item list would
    incorrectly apply one item's sitewide/relevance tiering across all of them.
    """
    if not already_selected:
        coupons = await select_top_coupons(coupons, user_message, quota=quota)
    if not coupons:
        yield "I couldn't find coupons that specifically match what you're looking for on GrabOn right now."
        return

    coupons  = _prioritise_coupons(coupons)

    history  = conv.get_history(session_id)
    messages = _history_to_messages(history)
    messages.append({"role": "user", "content": user_message})

    summary    = _coupon_summary(coupons)
    system_raw = _get_system_prompt(for_narrowing=False)
    system     = system_raw.replace("{coupon_summary}", summary)

    llm = get_llm()

    async for chunk in llm.generate(
        system_prompt = system,
        messages      = messages,
        temperature   = config.LLM_RESPOND_TEMPERATURE,
        max_tokens    = config.LLM_MAX_TOKENS,
    ):
        yield chunk

    llm_logger.log_call(
        model         = llm.model,
        prompt_file   = f"respond_{config.LLM_PROVIDER}.txt",
        function_name = "stream_coupon_response",
        input_tokens  = llm.last_usage.get("input_tokens", 0),
        output_tokens = llm.last_usage.get("output_tokens", 0),
        session_id    = session_id,
    )

    # After text stream, emit structured coupon data
    yield {"type": "coupons", "data": _serialise_coupons(coupons)}


def _serialise_coupons(coupons: list[dict]) -> list[dict]:
    """Convert coupon dicts to JSON-safe format for the frontend."""
    safe = []
    for c in coupons:
        safe.append({
            "couponId":         c.get("CouponID"),
            "storeName":        c.get("StoreName", ""),
            "couponName":       c.get("CouponName", ""),
            "couponCode":       c.get("CouponCode") or "",
            "couponUrl":        c.get("CouponUrl") or "",
            "couponTypeId":     c.get("CouponTypeID"),
            "discount":         float(c["Discount"]) if c.get("Discount") else 0,
            "discountDisplay":  c.get("discount_display", ""),
            "minOrderAmount":   float(c["MinimumOrderAmount"]) if c.get("MinimumOrderAmount") else None,
            "maxDiscount":      float(c["MaximumDiscount"]) if c.get("MaximumDiscount") else None,
            "verified":         bool(c.get("Verified")),
            "exclusive":        bool(c.get("Exclusive")),
            "hotOffer":         bool(c.get("HotOffer")),
            "bestOffer":        bool(c.get("BestOffer")),
            "forExistingUser":  bool(c.get("ForExistingUser")),
            "validityLabel":    c.get("validity_label", ""),
            "validityUrgency":  c.get("validity_urgency", "valid"),
            "endDate":          c["EndDate"].isoformat() if c.get("EndDate") else None,
        })
    return safe
