"""
Level 4: LLM response generation with SSE streaming.
Handles both coupon responses and conversational narrowing questions.
"""

import json
import logging
import re
from pathlib import Path
from typing import AsyncIterator

from openai import AsyncOpenAI

import config
import coupon_tiers
from llm.factory import get_llm
import conversation as conv
import llm_logger

log = logging.getLogger(__name__)


def _load_prompt(filename: str) -> str:
    path = config.PROMPTS_DIR / filename
    return path.read_text(encoding="utf-8")


def _coupon_summary(coupons: list[dict]) -> str:
    """
    Compact, fully-accurate natural-language summary for the LLM prompt.
    The response prompt cites facts straight from this string, so every fact
    here must be literally true -- an ambiguous or missing figure is exactly
    what causes the model to invent one instead.
    """
    if not coupons:
        return "no coupons found"
    # Sample stores from the FULL result set, not just the first 3 — when multiple
    # verticals/stores are merged (e.g. Laptop + Cab), the first 3 entries can all
    # belong to whichever group was fetched first, silently hiding the others
    # from the summary the LLM uses to write its opening sentence.
    stores  = sorted({c.get("StoreName", "") for c in coupons if c.get("StoreName")})
    n_today = sum(1 for c in coupons if c.get("validity_urgency") == "expires_today")
    n_soon  = sum(1 for c in coupons if c.get("validity_urgency") == "expires_soon")
    # Only trust Discount as a clean percentage when CouponTypeID says it actually
    # IS one (type 2) -- some rows store a flat rupee amount or a promo-mechanic ID
    # in the same column, so "% off" would be a lie for those.
    pct_discounts = [c.get("Discount") or 0 for c in coupons if c.get("CouponTypeID") == 2]
    best_pct = max(pct_discounts) if pct_discounts else 0

    store_str = ", ".join(stores[:3]) + ("..." if len(stores) > 3 else "")
    parts = [f"Found top deals across: {store_str}.", f"{len(coupons)} deals found."]
    if n_today:
        parts.append(f"{n_today} expire TODAY.")
    elif n_soon:
        parts.append(f"{n_soon} expiring soon.")
    if best_pct >= 50:
        parts.append(f"Top discount: {int(best_pct)}% off.")
    return " ".join(parts)


def _history_to_messages(history: list[conv.Message]) -> list[dict]:
    return [{"role": m.role, "content": m.content} for m in history]


def _get_system_prompt(for_narrowing: bool = False) -> str:
    if for_narrowing:
        return _load_prompt("narrowing.txt")
    provider = config.LLM_PROVIDER.lower()
    filename = f"respond_{provider}.txt"
    if not (config.PROMPTS_DIR / filename).exists():
        filename = "respond_ollama.txt"
    return _load_prompt(filename)


async def stream_narrowing_question(
    clarification_question: str,
    user_message: str,
    session_id: str,
) -> AsyncIterator[str]:
    """
    Stream clarification question for vague (Type C) queries.
    The question is already generated by the LLM classifier — yield it directly.
    Falls back to a second LLM call only if the classifier returned nothing.
    """
    if clarification_question:
        yield clarification_question
        return

    # Fallback: ask LLM to generate a narrowing question
    history  = await conv.get_history(session_id)
    messages = _history_to_messages(history)
    messages.append({"role": "user", "content": user_message})

    system = _get_system_prompt(for_narrowing=True)
    llm    = get_llm()
    async for chunk in llm.generate(
        system_prompt = system,
        messages      = messages,
        temperature   = config.LLM_RESPOND_TEMPERATURE,
        max_tokens    = 150,
    ):
        yield chunk
    llm_logger.log_call(
        model         = llm.model,
        prompt_file   = "narrowing.txt",
        function_name = "stream_narrowing_question",
        input_tokens  = llm.last_usage.get("input_tokens", 0),
        output_tokens = llm.last_usage.get("output_tokens", 0),
        session_id    = session_id,
    )


async def stream_unavailable_response(
    user_message: str,
    session_id: str,
    subject: str,
) -> AsyncIterator[str]:
    """
    Warm, natural "we don't have that right now" reply that explicitly names
    what was asked for -- never a stock template, never the same wording twice.
    No alternative store/category is ever suggested; this only declines and
    invites the user to ask for something else.
    """
    prompt = (
        f"The user asked for coupons related to \"{subject}\", but GrabOn has no "
        f"active coupon codes for that right now.\n\n"
        f"Write a warm, natural, one-off reply telling them this plainly and "
        f"politely. Mention \"{subject}\" by name so they know you understood "
        f"exactly what they asked for. Do not suggest any other store or "
        f"category yourself -- just invite them to ask for something else if "
        f"they'd like.\n\n"
        f"Vary your phrasing every time, including your OPENING WORDS -- do not "
        f"default to \"I understand you're looking for...\" or any other fixed "
        f"opener. Pick a fresh angle each time: sometimes lead with the apology, "
        f"sometimes with the store name, sometimes with the invitation to ask "
        f"for something else. Never reuse a stock template.\n\n"
        f"Max 2 sentences, under 35 words. No em dashes. No exclamation marks. "
        f"No corporate phrasing (\"I'd be happy to\")."
    )
    history  = await conv.get_history(session_id)
    messages = _history_to_messages(history)
    messages.append({"role": "user", "content": prompt})

    llm = get_llm()
    full_text = ""
    async for chunk in llm.generate(
        system_prompt = "You are GrabonGPT, a friendly coupon assistant for GrabOn.in.",
        messages      = messages,
        temperature   = 0.8,  # higher than normal -- the whole point is varied phrasing
        max_tokens    = 80,
    ):
        yield chunk
        full_text += chunk
    llm_logger.log_call(
        model         = llm.model,
        prompt_file   = "inline: unavailable_response",
        function_name = "stream_unavailable_response",
        input_tokens  = llm.last_usage.get("input_tokens", 0),
        output_tokens = llm.last_usage.get("output_tokens", 0),
        session_id    = session_id,
    )


_openai_client: AsyncOpenAI | None = None


def _get_openai() -> AsyncOpenAI:
    global _openai_client
    if _openai_client is None:
        _openai_client = AsyncOpenAI(api_key=config.OPENAI_API_KEY)
    return _openai_client


async def filter_brand_coupons(brand: str, coupons: list[dict]) -> list[dict]:
    """
    gpt-4o-mini verifies which CouponName-LIKE results are genuinely for the
    requested brand vs. just mentioning it incidentally (e.g. multi-brand listings).
    Returns [] if nothing qualifies. Falls back to all on parse error.
    """
    def _disc(c: dict) -> str:
        disp = c.get("discount_display") or ""
        if disp:
            return disp
        d = c.get("Discount")
        return f"{int(d)}% OFF" if d else "flat discount"

    index_map = {
        i: {
            "store":    c.get("StoreName") or "",
            "name":     (c.get("CouponName") or "").strip(),
            "discount": _disc(c),
        }
        for i, c in enumerate(coupons)
    }

    prompt = (
        f"User asked for \"{brand}\" coupons.\n\n"
        f"These coupons were found by searching CouponName for \"{brand}\":\n"
        f"{json.dumps(index_map, indent=2)}\n\n"
        f"KEEP a coupon if ANY of these are true:\n"
        f"  - The store name contains \"{brand}\"\n"
        f"  - The coupon name mentions buying, purchasing, or getting a discount specifically on {brand} products\n"
        f"  - The coupon is a {brand}-specific offer (e.g. \"{brand} Special Offer\", \"Purchase Of {brand}\")\n"
        f"EXCLUDE only if {brand} appears alongside 5+ other brand names (pure multi-brand listing) "
        f"or is mentioned completely incidentally with no relation to the discount.\n"
        f"When in doubt, KEEP the coupon.\n"
        f"Return a JSON array of indices only, e.g. [0, 2]. Return [] if none qualify. No explanation."
    )

    try:
        client = _get_openai()
        resp = await client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"},
            temperature=0,
            max_tokens=100,
        )
        llm_logger.log_call(
            model         = "gpt-4o-mini",
            prompt_file   = "inline: brand_filter",
            function_name = "filter_brand_coupons",
            input_tokens  = resp.usage.prompt_tokens     or 0,
            output_tokens = resp.usage.completion_tokens or 0,
        )
        raw = resp.choices[0].message.content or ""
        parsed = json.loads(raw)
        indices = parsed if isinstance(parsed, list) else next(
            (v for v in parsed.values() if isinstance(v, list)), None
        )
        if indices is None:
            return coupons  # parse error → safe fallback
        # Defensive: flatten -- the model can occasionally wrap indices in an
        # extra list layer (confirmed in production) even under json_object mode.
        flat = _flatten_ints(indices)
        return [coupons[i] for i in flat if 0 <= i < len(coupons)]
    except Exception as e:
        log.warning("Brand coupon filter failed, returning all: %s", e)
        return coupons


def _flatten_ints(v: list) -> list[int]:
    """Recursively flatten nested lists down to plain ints, dropping anything else."""
    out: list[int] = []
    for item in v:
        if isinstance(item, bool):
            continue  # bool is technically an int subclass in Python -- never a valid index
        if isinstance(item, int):
            out.append(item)
        elif isinstance(item, list):
            out.extend(_flatten_ints(item))
    return out


async def _classify_relevant_groups(
    groups: dict[str, list[dict]], user_message: str
) -> dict[str, list[int]]:
    """
    One combined gpt-4o-mini call. `groups` maps an item label (e.g. "bus", "hotel",
    or "_single" for a one-item query) to a list of {"store", "name"} candidates
    (sitewide and synonym-tier coupons from a single-store pool are already pulled
    out in pure Python before this is called -- the LLM's only job is semantic
    relevance, nothing it could get by exact keyword match).

    The store name travels with each candidate specifically so the model can judge
    STORE-TYPE fit, not just literal keyword overlap in the coupon text -- a broad
    vertical mixes unrelated businesses (a bakery next to a food-delivery platform),
    and without knowing which store a coupon belongs to, "no literal keyword match"
    and "wrong kind of business entirely" look identical to a text-only filter.

    Returns {label: [indices into that group's own list]}. Empty list per group on
    error or when that item's ask was generic (no specific product/category).
    """
    non_empty = {k: v for k, v in groups.items() if v}
    if not non_empty:
        return {k: [] for k in groups}

    prompt = (
        f"User asked: \"{user_message}\"\n\n"
        f"Coupons grouped by item, each with its store:\n{json.dumps(non_empty, indent=2)}\n\n"
        f"For EACH group, decide which coupons genuinely match what the user asked for "
        f"regarding that specific item (a brand, product type, or category mentioned in "
        f"the request), and return their indices within that group's own list.\n"
        f"Judge by STORE TYPE and PRODUCT specifics, not just literal keyword overlap:\n"
        f"  - KEEP a store whose business plausibly sells or delivers what was asked, "
        f"even if the coupon text is generic (e.g. a food-delivery platform's 'flat "
        f"50% off orders' coupon is a genuine match for a biriyani/noodles/veg-meal request).\n"
        f"  - EXCLUDE a store whose business is clearly the wrong category for what was "
        f"asked, even if its coupon looks like a big generic discount (e.g. a bakery is "
        f"NOT a match for a biriyani request; a laptop-specific coupon naming a laptop "
        f"model number is NOT a match for an earbuds/headphones request even though both "
        f"are 'electronics' -- wrong product beats any discount size).\n"
        f"  - EXCLUDE a coupon if it is specifically for a DIFFERENT product than the one requested, "
        f"even if they are in the same general category (e.g. a washing-machine-specific or vacuum-cleaner-specific "
        f"coupon is NOT a match for a dishwasher request; a TV-specific coupon is NOT a match for a laptop request).\n"
        f"If the ask for an item was a generic store-only request with no specific "
        f"product/category, return an empty indices list for that group — a generic ask "
        f"has nothing to be more specific than.\n"
        f"Return one result entry per group, using the exact group key as \"group\"."
    )

    schema = {
        "type": "object",
        "properties": {
            "results": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "group":   {"type": "string"},
                        "indices": {"type": "array", "items": {"type": "integer"}},
                    },
                    "required": ["group", "indices"],
                    "additionalProperties": False,
                },
            },
        },
        "required": ["results"],
        "additionalProperties": False,
    }

    try:
        client = _get_openai()
        resp = await client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            response_format={
                "type": "json_schema",
                "json_schema": {"name": "relevance_classification", "strict": True, "schema": schema},
            },
            temperature=0,
            max_tokens=800,
        )
        llm_logger.log_call(
            model         = "gpt-4o-mini",
            prompt_file   = "inline: tier_relevance",
            function_name = "_classify_relevant_groups",
            input_tokens  = resp.usage.prompt_tokens     or 0,
            output_tokens = resp.usage.completion_tokens or 0,
        )
        raw = resp.choices[0].message.content or ""
        if resp.choices[0].finish_reason == "length":
            log.warning("Relevance classification hit max_tokens -- response likely truncated")
        parsed = json.loads(raw)
        by_group = {r.get("group"): r.get("indices") for r in parsed.get("results", []) if isinstance(r, dict)}
        # Structured outputs guarantees the schema (array of plain ints per group),
        # but still defend against a missing group key (e.g. model renamed it) by
        # flattening whatever comes back rather than trusting the shape blindly.
        return {k: (_flatten_ints(by_group[k]) if isinstance(by_group.get(k), list) else []) for k in groups}
    except Exception as e:
        log.warning("Relevance classification failed, falling back to all-relevant: %s", e)
        return {k: list(range(len(v))) for k, v in groups.items()}


def _discount_value(c: dict) -> tuple[bool, float]:
    """
    Sort key for 'best discount' ranking within a tier. Percentage discounts
    (CouponTypeID 2, a bounded 0-100 scale) always sort ahead of flat-rupee or
    any other discount type -- a flat Rs 26,000 discount just reflects how
    expensive the underlying product is (almost always a laptop or similarly
    big-ticket item), not how good or relevant the deal is. Comparing that raw
    number against a 50% figure and letting the bigger number win is how an
    unrelated big-ticket coupon dominates every "best discount" catch-all,
    including when the whole point of the catch-all was to find something
    plausible for an unrelated, cheaper product category.
    """
    is_pct = c.get("CouponTypeID") == 2
    value  = float(c.get("Discount") or 0)
    return (is_pct, value)


async def select_top_coupons_for_items(
    item_coupons: dict[str, list[dict]],
    user_message: str,
    quota_per_item: int,
    store_scoped: bool = False,
) -> dict[str, list[dict]]:
    """
    4-tier priority fill, per item: sitewide -> relevant -> synonym -> best-discount
    catch-all. Always tries to fill `quota_per_item` by falling through tiers in
    order. One combined LLM call covers relevance for every item at once.
    Dedups by exact CouponCode within each item's result (a coupon picked into an
    earlier tier is never eligible for a later tier).

    The sitewide/synonym keyword tiers only get priority when store_scoped=True
    -- meaning the CALLER already knows the user named (or was matched to) a
    specific store, so "sitewide" means that store's own blanket offer,
    inherently relevant. This must come from the actual routing decision, not
    be guessed from the data: a broad vertical fetch can easily contain only
    one store's coupons by coincidence (e.g. "earbuds" resolving to a vertical
    where HP Shopping happens to be the only store with live codes indexed),
    and that coincidence has nothing to do with whether the user asked about
    HP specifically. Trusting "only one MerchantID in this batch" as a proxy
    for "the user asked for this store" is exactly how an unrelated laptop
    store's coupon out-ranked genuine earbuds relevance. When store_scoped is
    False, everything goes through relevance judgment on equal footing.
    """
    per_item_tiers: dict[str, dict] = {}
    for label, coupons in item_coupons.items():
        sitewide, synonym, leftover = [], [], []
        if store_scoped:
            for c in coupons:
                tier = coupon_tiers.classify_keyword_tier(c.get("CouponName") or "")
                if tier == "sitewide":
                    sitewide.append(c)
                elif tier == "synonym":
                    synonym.append(c)
                else:
                    leftover.append(c)
        else:
            leftover = list(coupons)

        per_item_tiers[label] = {"sitewide": sitewide, "synonym": synonym, "leftover": leftover}

    name_groups = {
        label: [
            {"store": c.get("StoreName") or "", "name": (c.get("CouponName") or "").strip()}
            for c in t["leftover"]
        ]
        for label, t in per_item_tiers.items()
    }
    relevant_by_item = await _classify_relevant_groups(name_groups, user_message)

    results: dict[str, list[dict]] = {}
    for label, t in per_item_tiers.items():
        leftover = t["leftover"]
        rel_idx  = {i for i in (relevant_by_item.get(label) or []) if isinstance(i, int) and 0 <= i < len(leftover)}
        relevant  = [leftover[i] for i in sorted(rel_idx)]
        catch_all = [c for i, c in enumerate(leftover) if i not in rel_idx]

        if store_scoped:
            buckets = [t["sitewide"], relevant, t["synonym"], catch_all]
        else:
            buckets = [relevant]

        for b in buckets:
            b.sort(key=_discount_value, reverse=True)

        picked: list[dict] = []
        seen_codes: set[str] = set()
        for bucket in buckets:
            if len(picked) >= quota_per_item:
                break
            for c in bucket:
                if len(picked) >= quota_per_item:
                    break
                code = (c.get("CouponCode") or "").strip()
                if code and code in seen_codes:
                    continue  # already picked in an earlier tier — never show twice
                seen_codes.add(code)
                picked.append(c)
        results[label] = picked

    return results


async def select_top_coupons(
    coupons: list[dict], user_message: str, quota: int = 3, store_scoped: bool = False,
) -> list[dict]:
    """Single-item convenience wrapper around select_top_coupons_for_items."""
    result = await select_top_coupons_for_items(
        {"_single": coupons}, user_message, quota, store_scoped=store_scoped,
    )
    return result["_single"]


def serialise_coupons(coupons: list[dict]) -> list[dict]:
    """Public wrapper used by main.py to emit coupons without a full LLM call."""
    return _serialise_coupons(_prioritise_coupons(coupons))


def _prioritise_coupons(coupons: list[dict]) -> list[dict]:
    """Put coupons with actual codes first; deal-link-only coupons last."""
    with_code    = [c for c in coupons if (c.get("CouponCode") or "").strip()]
    without_code = [c for c in coupons if not (c.get("CouponCode") or "").strip()]
    return with_code + without_code


async def stream_coupon_response(
    user_message: str,
    session_id: str,
    coupons: list[dict],
    pending_offer: str = "",
    quota: int = 3,
    already_selected: bool = False,
    store_scoped: bool = False,
) -> AsyncIterator[str | dict]:
    """
    Stream the LLM coupon response.
    Yields str chunks (text tokens) then a final dict {"type": "coupons", "data": [...]}.
    By default runs the 4-tier priority selector (sitewide -> relevant -> synonym ->
    best-discount), always capping to `quota`. Pass already_selected=True only when
    the caller already ran select_top_coupons_for_items across multiple items and
    merged the results — re-running selection on a mixed multi-item list would
    incorrectly apply one item's sitewide/relevance tiering across all of them.

    store_scoped must reflect the actual routing decision (did the user name a
    specific store?), never be inferred from the coupon data itself -- a broad
    vertical fetch can coincidentally contain only one store's coupons with no
    connection to user intent. Defaults to False, the safe choice: relevance
    leads unless the caller can affirmatively say this pool is one named store.
    """
    if not already_selected:
        coupons = await select_top_coupons(coupons, user_message, quota=quota, store_scoped=store_scoped)
    if not coupons:
        yield "I couldn't find coupons that specifically match what you're looking for on GrabOn right now."
        return

    coupons  = _prioritise_coupons(coupons)

    history  = await conv.get_history(session_id)
    messages = _history_to_messages(history)
    messages.append({"role": "user", "content": user_message})

    summary    = _coupon_summary(coupons)
    system_raw = _get_system_prompt(for_narrowing=False)
    system     = system_raw.replace("{coupon_summary}", summary)

    llm = get_llm()

    async for chunk in llm.generate(
        system_prompt = system,
        messages      = messages,
        temperature   = config.LLM_RESPOND_TEMPERATURE,
        max_tokens    = config.LLM_MAX_TOKENS,
    ):
        yield chunk

    llm_logger.log_call(
        model         = llm.model,
        prompt_file   = f"respond_{config.LLM_PROVIDER}.txt",
        function_name = "stream_coupon_response",
        input_tokens  = llm.last_usage.get("input_tokens", 0),
        output_tokens = llm.last_usage.get("output_tokens", 0),
        session_id    = session_id,
    )

    # After text stream, emit structured coupon data
    yield {"type": "coupons", "data": _serialise_coupons(coupons)}


def _build_logo_url(website: str) -> str:
    """Build a Google Favicon URL from a store's website domain."""
    if not website:
        return ""
    host = website.lower().strip()
    host = re.sub(r"^[a-z]+://", "", host)
    host = host.split("/", 1)[0]
    if not host:
        return ""
    return f"https://www.google.com/s2/favicons?domain={host}&sz=64"


def _serialise_coupons(coupons: list[dict]) -> list[dict]:
    """Convert coupon dicts to JSON-safe format for the frontend."""
    safe = []
    for c in coupons:
        safe.append({
            "couponId":         c.get("CouponID"),
            "storeName":        c.get("StoreName", ""),
            "storeLogoUrl":     _build_logo_url(c.get("StoreWebsite", "")),
            "couponName":       c.get("CouponName", ""),
            "couponCode":       c.get("CouponCode") or "",
            "couponUrl":        c.get("CouponUrl") or "",
            "couponTypeId":     c.get("CouponTypeID"),
            "discount":         float(c["Discount"]) if c.get("Discount") else 0,
            "discountDisplay":  c.get("discount_display", ""),
            "minOrderAmount":   float(c["MinimumOrderAmount"]) if c.get("MinimumOrderAmount") else None,
            "maxDiscount":      float(c["MaximumDiscount"]) if c.get("MaximumDiscount") else None,
            "verified":         bool(c.get("Verified")),
            "exclusive":        bool(c.get("Exclusive")),
            "hotOffer":         bool(c.get("HotOffer")),
            "bestOffer":        bool(c.get("BestOffer")),
            "forExistingUser":  bool(c.get("ForExistingUser")),
            "validityLabel":    c.get("validity_label", ""),
            "validityUrgency":  c.get("validity_urgency", "valid"),
            "endDate":          c["EndDate"].isoformat() if c.get("EndDate") else None,
        })
    return safe
